"""Add history and user relations to models

Revision ID: 07099e20d314
Revises: b7302b9b66f6
Create Date: 2025-06-06 23:02:22.341295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07099e20d314'
down_revision = 'b7302b9b66f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_estados_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('fecha_cambio', sa.DateTime(), nullable=True),
    sa.Column('usuario_cambio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_cambio_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('business_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('business_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_table('historial_estados_pedido')
    # ### end Alembic commands ###
