"""elimina columnas antiguas paquete envio

Revision ID: 172f3d45feec
Revises: 8e1a74ab3fee
Create Date: 2026-02-02 23:43:19.547340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172f3d45feec'
down_revision = '8e1a74ab3fee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalles_paquete_envio', schema=None) as batch_op:
        batch_op.drop_column('peso_kg')
        batch_op.drop_column('dimensiones_cm')
        batch_op.drop_column('instrucciones_especiales')
        batch_op.drop_column('valor_declarado')
        batch_op.drop_column('tipo_paquete')
        batch_op.drop_column('tamano_paquete')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalles_paquete_envio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tamano_paquete', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tipo_paquete', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('valor_declarado', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('instrucciones_especiales', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dimensiones_cm', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('peso_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
