"""Adicion nuevo campo estado en tbl orders

Revision ID: 34e0a2be003e
Revises: 2185507a0f8d
Create Date: 2026-02-20 21:49:22.015063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34e0a2be003e'
down_revision = '2185507a0f8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('driver_status')

    # ### end Alembic commands ###
