"""add_colum_serviceid_detallepqueteenvio

Revision ID: 43ec28f3f482
Revises: e6163ddac42a
Create Date: 2025-06-11 19:57:58.906332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ec28f3f482'
down_revision = 'e6163ddac42a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalles_paquete_envio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servicio_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'services', ['servicio_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalles_paquete_envio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('servicio_id')

    # ### end Alembic commands ###
