"""Initial schema setup including new tables and relationships

Revision ID: 65ea3e78f77e
Revises: 
Create Date: 2025-06-04 23:53:43.688936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65ea3e78f77e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detalles_item_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion_item', sa.Text(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_estimado', sa.Float(), nullable=True),
    sa.Column('notas_especificas', sa.Text(), nullable=True),
    sa.Column('tienda_preferida', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('customers_user_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_customers_phone_number'))
        batch_op.drop_index(batch_op.f('ix_customers_user_id'))
        batch_op.create_index(batch_op.f('ix_customers_user_id'), ['user_id'], unique=True)
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=True),
    sa.Column('is_principal', sa.Boolean(), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('rating',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
        batch_op.drop_constraint(batch_op.f('businesses_slug_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('businesses_user_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_businesses_name'))
        batch_op.drop_index(batch_op.f('ix_businesses_slug'))
        batch_op.create_index(batch_op.f('ix_businesses_slug'), ['slug'], unique=True)
        batch_op.drop_index(batch_op.f('ix_businesses_user_id'))
        batch_op.create_index(batch_op.f('ix_businesses_user_id'), ['user_id'], unique=True)
        
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.alter_column('vehicle_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('rating',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
        batch_op.drop_constraint(batch_op.f('drivers_user_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_drivers_license_plate'))
        batch_op.drop_index(batch_op.f('ix_drivers_phone_number'))
        batch_op.drop_index(batch_op.f('ix_drivers_user_id'))
        batch_op.create_index(batch_op.f('ix_drivers_user_id'), ['user_id'], unique=True)
    op.create_table('detalles_paquete_envio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_paquete', sa.String(length=255), nullable=False),
    sa.Column('direccion_recogida', sa.Text(), nullable=False),
    sa.Column('tamano_paquete', sa.String(length=20), nullable=True),
    sa.Column('direccion_entrega', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('origen_direccion_id', sa.Integer(), nullable=True),
    sa.Column('destino_direccion_id', sa.Integer(), nullable=True),
    sa.Column('peso_kg', sa.Float(), nullable=True),
    sa.Column('dimensiones_cm', sa.String(length=50), nullable=True),
    sa.Column('valor_declarado', sa.Float(), nullable=True),
    sa.Column('instrucciones_especiales', sa.Text(), nullable=True),
    sa.Column('precio_calculado', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['destino_direccion_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['origen_direccion_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_categories_business_id'))
        batch_op.drop_index(batch_op.f('ix_business_categories_category_id'))

    with op.batch_alter_table('business_payment_methods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_payment_methods_business_id'))
        batch_op.drop_index(batch_op.f('ix_business_payment_methods_payment_method_id'))


    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_categories_name'))

    with op.batch_alter_table('opening_hours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('open_time', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('close_time', sa.Time(), nullable=False))
        batch_op.alter_column('day_of_week',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_opening_hours_day_of_week'))
        batch_op.drop_column('hours')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_item', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('paquete_envio_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('item_compra_id', sa.Integer(), nullable=True))
        batch_op.alter_column('price_at_order',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_order_items_product_id'))
        batch_op.create_foreign_key(None, 'detalles_paquete_envio', ['paquete_envio_id'], ['id'])
        batch_op.create_foreign_key(None, 'detalles_item_compra', ['item_compra_id'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_business_id'))
        batch_op.drop_index(batch_op.f('ix_orders_customer_id'))
        batch_op.drop_index(batch_op.f('ix_orders_driver_id'))
        batch_op.drop_index(batch_op.f('ix_orders_order_time'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_column('payment_method')

    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_payment_methods_name'))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_products_is_available'))
        batch_op.drop_index(batch_op.f('ix_products_name'))
        batch_op.drop_column('category')

    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_products_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_is_available'), ['is_available'], unique=False)
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_methods_name'), ['name'], unique=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('is_active')
        batch_op.drop_column('description')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_order_time'), ['order_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_business_id'), ['business_id'], unique=False)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_order_items_product_id'), ['product_id'], unique=False)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('price_at_order',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('item_compra_id')
        batch_op.drop_column('paquete_envio_id')
        batch_op.drop_column('tipo_item')

    with op.batch_alter_table('opening_hours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hours', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.create_index(batch_op.f('ix_opening_hours_day_of_week'), ['day_of_week'], unique=False)
        batch_op.alter_column('day_of_week',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
        batch_op.drop_column('close_time')
        batch_op.drop_column('open_time')

    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drivers_user_id'))
        batch_op.create_index(batch_op.f('ix_drivers_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drivers_phone_number'), ['phone_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_drivers_license_plate'), ['license_plate'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('drivers_user_id_key'), ['user_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('rating',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('vehicle_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_user_id'))
        batch_op.create_index(batch_op.f('ix_customers_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_phone_number'), ['phone_number'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('customers_user_id_key'), ['user_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_name'), ['name'], unique=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_businesses_user_id'))
        batch_op.create_index(batch_op.f('ix_businesses_user_id'), ['user_id'], unique=False)
        batch_op.drop_index(batch_op.f('ix_businesses_slug'))
        batch_op.create_index(batch_op.f('ix_businesses_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_name'), ['name'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('businesses_user_id_key'), ['user_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('businesses_slug_key'), ['slug'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('rating',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('business_payment_methods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_payment_methods_payment_method_id'), ['payment_method_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_payment_methods_business_id'), ['business_id'], unique=False)

    with op.batch_alter_table('business_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_categories_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_categories_business_id'), ['business_id'], unique=False)

    op.drop_table('detalles_paquete_envio')
    op.drop_table('addresses')
    op.drop_table('services')
    op.drop_table('detalles_item_compra')
    # ### end Alembic commands ###
