"""Centralizar direcciones en la tabla Order real

Revision ID: 6fc98fde8377
Revises: b653cf75e09c
Create Date: 2025-06-14 21:57:55.446494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc98fde8377'
down_revision = 'b653cf75e09c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalles_paquete_envio', schema=None) as batch_op:
        batch_op.drop_column('direccion_entrega')
        batch_op.drop_column('direccion_recogida')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('direccion_recogida_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'addresses', ['direccion_recogida_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('direccion_recogida_id')
        batch_op.drop_column('pickup_address')

    with op.batch_alter_table('detalles_paquete_envio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion_recogida', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('direccion_entrega', sa.TEXT(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
