"""add deuda_customers_domiciliosRM_14062025

Revision ID: 849bd4d6335f
Revises: f7028277cf0d
Create Date: 2025-06-14 10:03:38.505499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '849bd4d6335f'
down_revision = 'f7028277cf0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deuda_cancelacion', sa.Numeric(precision=10, scale=2), nullable=False))

    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.alter_column('saldo_cuenta',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.alter_column('saldo_cuenta',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('deuda_cancelacion')

    # ### end Alembic commands ###
