"""simplifica detalles paquete envio

Revision ID: 8e1a74ab3fee
Revises: d1f87baccc45
Create Date: 2026-02-02 18:58:35.423355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e1a74ab3fee'
down_revision = 'd1f87baccc45'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Agregar columnas como NULLABLE
    with op.batch_alter_table('detalles_paquete_envio', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('nombre_quien_recibe', sa.String(length=100), nullable=True)
        )
        batch_op.add_column(
            sa.Column('telefono_quien_recibe', sa.String(length=20), nullable=True)
        )

    # 2. Rellenar datos por defecto para registros existentes
    op.execute("""
        UPDATE detalles_paquete_envio
        SET nombre_quien_recibe = 'No especificado'
        WHERE nombre_quien_recibe IS NULL
    """)

    op.execute("""
        UPDATE detalles_paquete_envio
        SET telefono_quien_recibe = '0000000000'
        WHERE telefono_quien_recibe IS NULL
    """)

    # 3. Convertir columnas a NOT NULL
    with op.batch_alter_table('detalles_paquete_envio', schema=None) as batch_op:
        batch_op.alter_column(
            'nombre_quien_recibe',
            nullable=False
        )
        batch_op.alter_column(
            'telefono_quien_recibe',
            nullable=False
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalles_paquete_envio', schema=None) as batch_op:
        batch_op.drop_column('telefono_quien_recibe')
        batch_op.drop_column('nombre_quien_recibe')

    # ### end Alembic commands ###
