"""Add addresses table, adjust types, and add services/enums 05062025_0022

Revision ID: b7302b9b66f6
Revises: 65ea3e78f77e
Create Date: 2025-06-05 00:22:18.099517

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b7302b9b66f6'
down_revision = '65ea3e78f77e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.alter_column('min_order_value',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('delivery_fee',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('servicio_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('order_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('costo_domicilio', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('direccion_entrega_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('payment_method_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('total_amount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_orders_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_servicio_id'), ['servicio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('orders_customer_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'services', ['servicio_id'], ['id'])
        batch_op.create_foreign_key(None, 'payment_methods', ['payment_method_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'addresses', ['direccion_entrega_id'], ['id'])
        batch_op.drop_column('delivery_fee')
        batch_op.drop_column('customer_notes')
        batch_op.drop_column('customer_id')
        batch_op.drop_column('service_fee')
        batch_op.drop_column('delivery_time')
        batch_op.drop_column('order_time')
        batch_op.drop_column('driver_notes')
        batch_op.drop_column('pickup_time')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('driver_notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('order_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('delivery_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('service_fee', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('customer_notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('delivery_fee', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('orders_customer_id_fkey'), 'customers', ['customer_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_orders_servicio_id'))
        batch_op.drop_index(batch_op.f('ix_orders_driver_id'))
        batch_op.drop_index(batch_op.f('ix_orders_business_id'))
        batch_op.alter_column('total_amount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('notes')
        batch_op.drop_column('payment_method_id')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('direccion_entrega_id')
        batch_op.drop_column('costo_domicilio')
        batch_op.drop_column('order_date')
        batch_op.drop_column('servicio_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.alter_column('delivery_fee',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('min_order_value',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###
