"""Hacer Order.business_id opcional y ajustar DetallesPaqueteEnvio

Revision ID: c8a03070847a
Revises: 43ec28f3f482
Create Date: 2025-06-11 21:57:00.390833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8a03070847a'
down_revision = '43ec28f3f482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalles_paquete_envio', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('detalles_paquete_envio_destino_direccion_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('detalles_paquete_envio_origen_direccion_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('detalles_paquete_envio_order_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('detalles_paquete_envio_servicio_id_fkey'), type_='foreignkey')
        batch_op.drop_column('servicio_id')
        batch_op.drop_column('destino_direccion_id')
        batch_op.drop_column('origen_direccion_id')
        batch_op.drop_column('order_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('direccion_entrega_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('direccion_entrega_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('business_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('detalles_paquete_envio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('origen_direccion_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('destino_direccion_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('servicio_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('detalles_paquete_envio_servicio_id_fkey'), 'services', ['servicio_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('detalles_paquete_envio_order_id_fkey'), 'orders', ['order_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('detalles_paquete_envio_origen_direccion_id_fkey'), 'addresses', ['origen_direccion_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('detalles_paquete_envio_destino_direccion_id_fkey'), 'addresses', ['destino_direccion_id'], ['id'])

    # ### end Alembic commands ###
