"""Se_incluye_columna_orderid_detalles_paquetes

Revision ID: e6163ddac42a
Revises: 07099e20d314
Create Date: 2025-06-11 02:40:43.996913

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e6163ddac42a'
down_revision = '07099e20d314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # PASO AÑADIDO: Actualizar los datos existentes ANTES de aplicar la restricción
    # ¡IMPORTANTE! Cambia '1' por el ID de negocio que sea correcto para tus datos.
    op.execute('UPDATE orders SET business_id = 1 WHERE business_id IS NULL')


    op.drop_table('payments')
    with op.batch_alter_table('detalles_paquete_envio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'])

    with op.batch_alter_table('historial_estados_pedido', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('historial_estados_pedido_usuario_cambio_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('historial_estados_pedido_pedido_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['usuario_cambio_id'], ['id'])
        batch_op.create_foreign_key(None, 'orders', ['pedido_id'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('business_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('business_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('historial_estados_pedido', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('historial_estados_pedido_pedido_id_fkey'), 'orders', ['pedido_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('historial_estados_pedido_usuario_cambio_id_fkey'), 'users', ['usuario_cambio_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('detalles_paquete_envio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('order_id')

    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('payment_method_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('payment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('payments_order_id_fkey')),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], name=op.f('payments_payment_method_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('payments_pkey')),
    sa.UniqueConstraint('order_id', name=op.f('payments_order_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
