"""Agregar saldo_cuenta a la tabla drivers

Revision ID: f7028277cf0d
Revises: c8a03070847a
Create Date: 2025-06-12 23:22:29.008888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7028277cf0d'
down_revision = 'c8a03070847a'
branch_labels = None
depends_on = None


def upgrade():
    
    #op.execute('UPDATE drivers SET saldo_cuenta = 0.0 WHERE saldo_cuenta IS NULL')
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saldo_cuenta', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_column('saldo_cuenta')

    # ### end Alembic commands ###
